### PR TITLE
Receptor client handles non-JSON error responses from receptor.

### PR DESCRIPTION
**Pull request by davidwadden**
As described in #13, Lattice is receiving empty error responses from the receptor client in certain cases.

We've made the receptor client more robust in dealing with non-JSON formatted responses.

Please review our pull request and let us know if you have any additional feedback.

Just a note:

We identified another place the receptor client would deliver an empty error.  If [client.go:257](https://github.com/cloudfoundry-incubator/receptor/compare/cloudfoundry-incubator:master...davidwadden:client-error-handling?expand=1#diff-d0b7f86cea13f90d3cc0cc2338da8d5fR257) returns an error, it will not be a `receptor.Error`.  This might happen from a 200 OK response that has malformed JSON.  We'd be willing to modify this PR to instead return a `receptor.Error{Type: InvalidJSON, Message: string(body)}` if this line returns an error.

Regards,
David

### CODE REVIEW

**Comment by luan** [comment]
Hi @davidwadden,

This is definitely something that needs to be solved.
We looked at the way you solved it and we think it might be cleaner if we look at the Content-Type of the response to chose which type of decoding we're going to do rather than expecting a JSON decode error.
Can you give that a shot and update the PR?

Thanks,
@luan && @fraenkel, CF Diego Team

**Comment by davidwadden** [comment]
thanks for considering our change and offering feedback.  i agree that sounds like a more elegant solution -- we'll work on updating the PR and reach out if we have further questions

david

**Comment by davidwadden** [comment]
We re-worked this pull request to look at the Content-Type before decoding as JSON.

Please take a look and let us know what you think.
@kaayell + @davidwadden

**Comment by davidwadden** [comment]
We tested the latest build of diego-release on master (*0.1235.0*) and it's working as expected!

```bash
✔ ~/workspace/diego-release/src/github.com/cloudfoundry-incubator/lattice [develop|✔]
08:23 $ ltc target happy.192.168.11.11.xip.io
Error verifying target: unknown_route
```

Thanks again!
@kaayell + @davidwadden

**Pull request closed without merging**
